[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "bernard-ledit"
version = "0.1.0"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "License :: OSI Approved :: MIT License",
]

[project.optional-dependencies]
test = [
    "pytest>=8",
    "pytest-xdist>=3",
]
lint = [
    "ruff",
    "mypy",
]
[tool.ruff]
line-length = 88
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "UP"]

[tool.maturin]
module-name = "bernard_ledit._bernard_ledit"
features = ["pyo3/extension-module"]
include = [
    "bernard_ledit/**/*.pyi",
    "bernard_ledit/libpdfium.so",
    "bernard_ledit/libpdfium.dylib",
    "bernard_ledit/pdfium.dll",
]

[tool.pytest.ini_options]
testpaths = ["bernard_ledit/tests"]
