from collections.abc import Iterable
from typing import overload

class Point:
    def __init__(self, x: float, y: float) -> None: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, value: float) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, value: float) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __getitem__(self, index: int) -> float: ...

PointInput = Point | tuple[float, float]

class Polygon:
    def __init__(self, points: Iterable[PointInput]) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> Point: ...
    @overload
    def __getitem__(self, index: slice) -> Polygon: ...
    def centroid(self) -> Point | None: ...
