class ImageError(Exception): ...

class Image:
    @property
    def size(self) -> tuple[int, int]: ...
    @property
    def format(self) -> str | None: ...
    def crop(self, left: int, top: int, right: int, bottom: int) -> Image: ...
    def resize(self, width: int, height: int, filter: str = "lanczos") -> Image: ...
    def encode(self, format: str, quality: int = 85, optimize: bool = False) -> bytes:
        ...
    def __repr__(self) -> str: ...

def decode(data: bytes) -> Image: ...
def guess_format(data: bytes) -> str: ...
def compress(
    data: bytes,
    quality: int = 85,
    max_width: int | None = None,
    max_height: int | None = None,
) -> tuple[bytes, int, int]: ...
