import os
from typing import BinaryIO

class ImageError(Exception): ...

class Image:
    @property
    def size(self) -> tuple[int, int]: ...
    @property
    def format(self) -> str | None: ...
    def crop(self, left: int, top: int, right: int, bottom: int) -> Image: ...
    def resize(self, width: int, height: int, filter: str = "lanczos") -> Image: ...
    def encode(
        self, format: str, quality: int = 85, optimize: bool = True
    ) -> bytes: ...
    def save(
        self,
        dest: str | os.PathLike[str] | BinaryIO,
        format: str | None = None,
        quality: int = 85,
        optimize: bool = True,
    ) -> None: ...
    def __repr__(self) -> str: ...

def decode(data: bytes | bytearray | BinaryIO) -> Image: ...
def guess_format(data: bytes | bytearray | BinaryIO) -> str: ...
def compress(
    data: bytes,
    quality: int = 85,
    max_width: int | None = None,
    max_height: int | None = None,
) -> tuple[bytes, int, int]: ...
