import os
from collections.abc import Iterator
from types import TracebackType
from typing import BinaryIO

class PdfiumError(Exception): ...

class PageSize:
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...

class PdfBitmap:
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    def to_bytes(self) -> bytes: ...
    def to_png_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class TextChar:
    def __init__(
        self,
        char: str,
        font_name: str,
        font_size: float,
        font_weight: int,
        stroke_color: tuple[int, int, int, int] | None = None,
        fill_color: tuple[int, int, int, int] | None = None,
        font_flags: int = 0,
        bounds: tuple[float, float, float, float] = (0.0, 0.0, 0.0, 0.0),
    ) -> None: ...
    @property
    def char(self) -> str: ...
    @property
    def font_name(self) -> str: ...
    @property
    def font_size(self) -> float: ...
    @property
    def font_weight(self) -> int: ...
    @property
    def stroke_color(self) -> tuple[int, int, int, int] | None: ...
    @property
    def fill_color(self) -> tuple[int, int, int, int] | None: ...
    @property
    def font_flags(self) -> int: ...
    @property
    def bounds(self) -> tuple[float, float, float, float]: ...
    def __repr__(self) -> str: ...

class PdfPage:
    def get_size(self) -> PageSize: ...
    def has_no_content(self) -> bool: ...
    def text(self) -> str: ...
    def chars(self) -> list[TextChar]: ...
    def rotation(self) -> int: ...
    def render(self, scale: float = 1.0) -> PdfBitmap: ...
    def __repr__(self) -> str: ...

PdfInput = bytes | str | os.PathLike | BinaryIO

class PdfDocument:
    def __init__(self, input: PdfInput) -> None: ...
    def __getitem__(self, index: int) -> PdfPage: ...
    def __iter__(self) -> Iterator[PdfPage]: ...
    @staticmethod
    def new() -> PdfDocument: ...
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...
    def get_page(self, index: int) -> PdfPage: ...
    def import_pages(self, src: PdfDocument, indexes: list[int]) -> None: ...
    def add_text(self, page_idx: int, chars: list[TextChar]) -> None: ...
    def save(self, buf: BinaryIO) -> None: ...
    def rasterize_page(self, page_index: int, quality: int) -> bytes: ...
    def close(self) -> None: ...
    def __repr__(self) -> str: ...
    def __enter__(self) -> PdfDocument: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> bool: ...
    def append_jpeg_page(self, jpeg_byte: bytes) -> None: ...
    def append_multiple_jpeg_pages(self, jpeg_bytes: list[bytes]) -> None: ...
    def save_to_file(self) -> None: ...
    def has_text(self) -> bool: ...
