from types import TracebackType
from typing import BinaryIO

class PdfiumError(Exception): ...

class PageSize:
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...

class PdfBitmap:
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    def to_bytes(self) -> bytes: ...
    def to_png_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class PdfPage:
    def get_size(self) -> PageSize: ...
    def is_empty(self) -> bool: ...
    def render(self, scale: float = 1.0) -> PdfBitmap: ...
    def __repr__(self) -> str: ...

PdfInput = bytes | BinaryIO

class PdfDocument:
    def __init__(self, input: PdfInput) -> None: ...
    @staticmethod
    def new() -> PdfDocument: ...
    def __len__(self) -> int: ...
    def get_page(self, index: int) -> PdfPage: ...
    def import_pages(self, src: PdfDocument, indexes: list[int]) -> None: ...
    def save(self, buf: BinaryIO) -> None: ...
    def close(self) -> None: ...
    def __repr__(self) -> str: ...
    def __enter__(self) -> PdfDocument: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> bool: ...
