name: Remote pre-commit

on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: extractions/setup-just@v4

      - name: Install PHP dev headers
        run: sudo apt-get install -y php-dev libclang-dev

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cargo tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny,cargo-hack,cargo-udeps

      - name: Check formatting
        run: just core format-check

      - name: Run Clippy
        run: just core clippy

      - name: Check feature matrix
        run: just core hack-check

      - name: Set up nightly Rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Check licenses and advisories
        run: just core check-deps
