name: Pull Request

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  workflow-lint:
    uses: ./.github/workflows/_workflow_lint.yml
  pre-commit:
    uses: ./.github/workflows/_pre-commit.yml
    needs: workflow-lint

  unit-tests:
    uses: ./.github/workflows/_unit-tests.yml
    needs: pre-commit

  python-binding-tests:
    uses: ./.github/workflows/_python-binding-tests.yml
    needs: unit-tests

  java-binding-tests:
    uses: ./.github/workflows/_java-binding-ci.yml
    needs: unit-tests
